# Generated by Django 5.2.15 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(db_index=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
